allowBuilds:
  '@nestjs/core': true
  '@openrouter/sdk': true
  better-sqlite3: true
  libxmljs2: true
  puppeteer: set this to true or false
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@hanivanrizky/nestjs-xpath-parser@0.3.1'
  - '@hanivanrizky/nestjs-browser-action@0.13.1'
onlyBuiltDependencies:
  - '@nestjs/core'
  - better-sqlite3
  - libxmljs2
  - unrs-resolver
overrides:
  puppeteer: npm:puppeteer-core@^24.38.0
