export enum CleanerType {
  PAGE_REGEX_REPLACE = 'regex-replace--page',
  PAGE_REGEX_EXTRACTION = 'regex-extraction--page',
  PAGE_QUERY_REMOVER = 'query-remover--page',
  URL_REGEX_REPLACE = 'regex-replace--url',
  URL_REGEX_EXTRACTION = 'regex-extraction--url',
  URL_QUERY_REMOVER = 'query-remover--url',
  REGEX_REPLACE = 'regex-replace',
  REGEX_EXTRACTION = 'regex-extraction',
  JSON_PATH = 'json-path',
  QUERY_REMOVER = 'query-remover',
  NUM_NORMALIZE = 'num-normalize',
  DATE_FORMAT = 'date-format',
  DATE_FORMAT_SPECIAL = 'date-format-special',
  PARSE_AS_URL = 'parse-as-url',
  EXTRACT_URL_PARAMS = 'extract-url-params',
  MEDIA_FILTER = 'media-filter',
}
