import { MigrationInterface, QueryRunner } from "typeorm";

export class InitDatabase1749263013286 implements MigrationInterface {
    name = 'InitDatabase1749263013286'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`queue_jobs\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`queue_name\` varchar(100) NOT NULL, \`job_data\` text NOT NULL, \`status\` enum ('waiting', 'active', 'completed', 'failed', 'delayed') NOT NULL DEFAULT 'waiting', \`attempts\` int NOT NULL DEFAULT '0', \`max_attempts\` int NOT NULL DEFAULT '3', \`scheduled_at\` timestamp NULL, \`processed_at\` timestamp NULL, \`error_message\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_5d66d6a093d8d7ac1a879b7a30\` (\`scheduled_at\`), INDEX \`IDX_68ced099a28e1d2d9b88223f64\` (\`status\`), INDEX \`IDX_61423160d46bd87e20380712aa\` (\`queue_name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`crawl_logs\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`job_id\` bigint UNSIGNED NOT NULL, \`level\` enum ('info', 'warning', 'error', 'debug') NOT NULL, \`message\` text NOT NULL, \`context\` json NULL, \`url\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_8796d9fb5c3a92b85a84fd53f8\` (\`created_at\`), INDEX \`IDX_15dd00f74d60c1b194e654a2c1\` (\`level\`), INDEX \`IDX_aea5b9190a22274d80784b7a03\` (\`job_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`crawl_jobs\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`job_id\` varchar(36) NOT NULL, \`source_id\` bigint UNSIGNED NOT NULL, \`job_type\` enum ('full_crawl', 'update_check', 'new_episodes', 'fix_broken_links') NOT NULL, \`status\` enum ('pending', 'running', 'completed', 'failed', 'cancelled') NOT NULL DEFAULT 'pending', \`priority\` int NOT NULL DEFAULT '0', \`parameters\` json NULL, \`scheduled_at\` timestamp NULL, \`started_at\` timestamp NULL, \`completed_at\` timestamp NULL, \`error_message\` text NULL, \`result_summary\` json NULL, \`retry_count\` int NOT NULL DEFAULT '0', \`max_retries\` int NOT NULL DEFAULT '3', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_9a2ecfc045315c5119c9caed35\` (\`scheduled_at\`), INDEX \`IDX_3080b5173e786addd7def0c82e\` (\`job_type\`), INDEX \`IDX_13ffa2e790ff4931f9b116e803\` (\`status\`), INDEX \`IDX_967b6d0bdab9d0811ea3d63316\` (\`source_id\`), UNIQUE INDEX \`IDX_218a9499fe36d693fe18a9d505\` (\`job_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`anime_update_history\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`anime_id\` bigint UNSIGNED NOT NULL, \`changes\` json NOT NULL, \`change_type\` enum ('new_episode', 'metadata_update', 'status_change', 'links_update') NOT NULL, \`source_trigger\` text NULL, \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_d98d6258f0b70918ee4b2060ab\` (\`updated_at\`), INDEX \`IDX_9564c07cc4861432b4ec9424d5\` (\`anime_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`download_links\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`episode_id\` bigint UNSIGNED NOT NULL, \`provider\` varchar(100) NOT NULL, \`url\` text NOT NULL, \`quality\` varchar(20) NOT NULL, \`format\` varchar(20) NULL, \`file_size_bytes\` bigint NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`last_checked_at\` timestamp NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_882318f0444faea04ee7d76ea6\` (\`quality\`), INDEX \`IDX_a5fb8506d10d1e5ec4e93a0154\` (\`provider\`), INDEX \`IDX_cddafb1e1ffdcc3fad35cf46d1\` (\`episode_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`episodes\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`anime_id\` bigint UNSIGNED NOT NULL, \`episode_number\` smallint NOT NULL, \`title\` varchar(255) NULL, \`source_episode_id\` varchar(100) NOT NULL, \`source_url\` text NOT NULL, \`thumbnail_url\` text NULL, \`description\` text NULL, \`duration_seconds\` int NULL, \`air_date\` date NULL, \`view_count\` int NOT NULL DEFAULT '0', \`download_count\` int NOT NULL DEFAULT '0', \`is_available\` tinyint NOT NULL DEFAULT 1, \`last_checked_at\` timestamp NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_bb36da96b51635996fc7fa4c7f\` (\`source_episode_id\`), INDEX \`IDX_9d3063c2bbc60082263d00c291\` (\`anime_id\`), UNIQUE INDEX \`IDX_5729db763fdc1c5a943593a8cb\` (\`anime_id\`, \`episode_number\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`genres\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`slug\` varchar(100) NOT NULL, \`description\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_f105f8230a83b86a346427de94\` (\`name\`), UNIQUE INDEX \`IDX_d1cbe4fe39bdfc77c76e94eada\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`anime\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`alternative_title\` varchar(255) NULL, \`synopsis\` text NULL, \`poster_url\` text NULL, \`banner_url\` text NULL, \`type\` enum ('tv', 'movie', 'ova', 'ona', 'special', 'music') NOT NULL DEFAULT 'tv', \`status\` enum ('ongoing', 'completed', 'upcoming', 'hiatus', 'cancelled') NOT NULL DEFAULT 'ongoing', \`total_episodes\` smallint NULL, \`release_year\` smallint NULL, \`season\` enum ('spring', 'summer', 'fall', 'winter') NULL, \`rating\` decimal(3,1) NULL, \`view_count\` int NOT NULL DEFAULT '0', \`download_count\` int NOT NULL DEFAULT '0', \`source_id\` bigint UNSIGNED NOT NULL, \`source_anime_id\` varchar(100) NOT NULL, \`source_url\` text NOT NULL, \`last_updated_at\` timestamp NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_5d0ffd2a6f4ce38af5e2f0a52f\` (\`release_year\`), INDEX \`IDX_ee8f7d2e05dacf165cb7badb19\` (\`type\`), INDEX \`IDX_fff1bb5201c112dbc7235cec57\` (\`status\`), UNIQUE INDEX \`IDX_3357ef66530ded8070af8db20b\` (\`source_id\`, \`source_anime_id\`), UNIQUE INDEX \`IDX_eb697220f0bea58bc6b034dc74\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sources\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`slug\` varchar(50) NOT NULL, \`base_url\` text NOT NULL, \`selectors\` json NULL, \`headers\` json NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`priority\` smallint NOT NULL DEFAULT '1', \`delay_ms\` int NOT NULL DEFAULT '5000', \`max_concurrent\` int NOT NULL DEFAULT '3', \`user_agent\` text NULL, \`timeout_seconds\` int NOT NULL DEFAULT '30', \`last_crawled_at\` timestamp NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_9a5cea873a16f3b91692a889d1\` (\`slug\`), UNIQUE INDEX \`IDX_9518ae1bc1cb241a19e4247624\` (\`is_active\`, \`priority\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`source_health\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`source_id\` bigint UNSIGNED NOT NULL, \`checked_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`is_accessible\` tinyint NOT NULL, \`response_time_ms\` int NULL, \`http_status_code\` int NULL, \`error_type\` enum ('network_error', 'timeout', 'dns_error', 'ssl_error', 'http_error', 'parsing_error', 'selector_error', 'validation_error', 'rate_limit', 'captcha', 'blocked', 'unknown') NULL, \`error_message\` text NULL, \`page_structure_changed\` tinyint NOT NULL DEFAULT 0, \`selectors_working_count\` int NOT NULL DEFAULT '0', \`selectors_failing_count\` int NOT NULL DEFAULT '0', INDEX \`IDX_3382deed6264090bdea4c03c11\` (\`is_accessible\`, \`checked_at\`), INDEX \`IDX_8809b5347e14710b28d9dfd2d8\` (\`source_id\`, \`checked_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`page_types\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`type_name\` enum ('home', 'anime_list', 'anime_detail', 'episode_list', 'episode_detail', 'search_results', 'genre_page', 'popular_page', 'latest_page', 'ongoing_page', 'completed_page') NOT NULL, \`description\` text NULL, UNIQUE INDEX \`IDX_237d2788374796cac460d70106\` (\`type_name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`url_templates\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`source_id\` bigint UNSIGNED NOT NULL, \`page_type_id\` bigint UNSIGNED NOT NULL, \`template_name\` varchar(100) NOT NULL, \`url_template\` text NOT NULL, \`parameter_schema\` json NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`priority\` smallint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_535b0f3055fea368253127eb7e\` (\`source_id\`, \`page_type_id\`, \`is_active\`), UNIQUE INDEX \`IDX_bb54bd9fe3cbfb212914178ba5\` (\`source_id\`, \`page_type_id\`, \`template_name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`url_patterns\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`source_id\` bigint UNSIGNED NOT NULL, \`page_type_id\` bigint UNSIGNED NOT NULL, \`pattern_name\` varchar(100) NOT NULL, \`regex_pattern\` text NOT NULL, \`parameter_mapping\` json NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`priority\` smallint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_423c12a15a879d69090f399d76\` (\`source_id\`, \`page_type_id\`, \`is_active\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`url_history\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`source_id\` bigint UNSIGNED NOT NULL, \`page_type_id\` bigint UNSIGNED NOT NULL, \`generated_url\` text NOT NULL, \`parameters\` json NULL, \`template_id\` bigint UNSIGNED NULL, \`last_crawled_at\` timestamp NULL, \`crawl_status\` enum ('pending', 'processing', 'success', 'failed', 'skipped', 'rate_limited') NOT NULL DEFAULT 'pending', \`response_status\` int NULL, \`error_message\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_6a3efcaf5f22c5fd41e663700e\` (\`last_crawled_at\`), INDEX \`IDX_f9589d4ba0d8cd0907a706b17f\` (\`source_id\`, \`page_type_id\`, \`crawl_status\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`source_headers\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`source_id\` bigint UNSIGNED NOT NULL, \`header_name\` varchar(100) NOT NULL, \`header_value\` text NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_8152d28e6dd1ad99e693ec7f6f\` (\`source_id\`, \`is_active\`), UNIQUE INDEX \`IDX_bf876dcdbfdd747a160338cb5e\` (\`source_id\`, \`header_name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`selector_types\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`type_name\` enum ('css', 'xpath', 'regex', 'json_path', 'text_contains', 'attribute', 'pseudo') NOT NULL, \`description\` text NULL, UNIQUE INDEX \`IDX_56a4ddb94ed60419498db630ff\` (\`type_name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`selectors\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`selector_type_id\` bigint UNSIGNED NOT NULL, \`selector_value\` text NOT NULL, \`description\` text NULL, \`version\` int NOT NULL DEFAULT '1', \`is_active\` tinyint NOT NULL DEFAULT 1, \`success_rate\` decimal(5,2) NOT NULL DEFAULT '0.00', \`last_tested_at\` timestamp NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_da03f3f8b37c9ffe0fa499e2ea\` (\`name\`), INDEX \`IDX_8d1bad2f2313c639e3c396c746\` (\`success_rate\`), INDEX \`IDX_d3a18a0a7df1bbadd26788cf4d\` (\`is_active\`, \`selector_type_id\`), UNIQUE INDEX \`IDX_497ad93eab57e405365304266c\` (\`name\`, \`version\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`selector_performance\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`selector_id\` bigint UNSIGNED NOT NULL, \`source_id\` bigint UNSIGNED NOT NULL, \`page_type_id\` bigint UNSIGNED NOT NULL, \`test_date\` date NOT NULL, \`total_attempts\` int NOT NULL DEFAULT '0', \`successful_extractions\` int NOT NULL DEFAULT '0', \`failed_extractions\` int NOT NULL DEFAULT '0', \`average_response_time_ms\` int NOT NULL DEFAULT '0', \`success_rate\` decimal(5,2) NOT NULL DEFAULT '0.00', INDEX \`IDX_a005831fdd760a68fef267822d\` (\`success_rate\`), INDEX \`IDX_16575e5e8cdd24246c64ac8022\` (\`test_date\`), UNIQUE INDEX \`IDX_8b29bfc2ce8062a6670f632ca1\` (\`selector_id\`, \`source_id\`, \`page_type_id\`, \`test_date\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`selector_fallbacks\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`primary_selector_id\` bigint UNSIGNED NOT NULL, \`fallback_selector_id\` bigint UNSIGNED NOT NULL, \`fallback_order\` smallint NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_0769c47ec4c57c433d7d7f5354\` (\`primary_selector_id\`, \`is_active\`), UNIQUE INDEX \`IDX_fbe135c9203e18689726da64d8\` (\`primary_selector_id\`, \`fallback_order\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`page_selectors\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`source_id\` bigint UNSIGNED NOT NULL, \`page_type_id\` bigint UNSIGNED NOT NULL, \`field_name\` varchar(100) NOT NULL, \`selector_id\` bigint UNSIGNED NOT NULL, \`is_required\` tinyint NOT NULL DEFAULT 0, \`extraction_rules\` json NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`priority\` smallint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_ec2101fb6578f5461937857ca5\` (\`source_id\`, \`page_type_id\`, \`is_active\`), UNIQUE INDEX \`IDX_ea564f9ee4653428fa6d12f94e\` (\`source_id\`, \`page_type_id\`, \`field_name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`crawl_strategies\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`source_id\` bigint UNSIGNED NOT NULL, \`page_type_id\` bigint UNSIGNED NOT NULL, \`strategy_name\` varchar(50) NOT NULL, \`use_browser\` tinyint NOT NULL DEFAULT 0, \`javascript_enabled\` tinyint NOT NULL DEFAULT 0, \`wait_for_selector\` varchar(255) NULL, \`wait_timeout\` int NOT NULL DEFAULT '10000', \`scroll_behavior\` enum ('none', 'top', 'bottom', 'element', 'lazy_load', 'infinite_scroll') NOT NULL DEFAULT 'none', \`request_delay_min\` int NOT NULL DEFAULT '1000', \`request_delay_max\` int NOT NULL DEFAULT '3000', \`max_retries\` int NOT NULL DEFAULT '3', \`configuration\` json NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_9c48bb32c66ff1e862eb5c63d3\` (\`source_id\`, \`is_active\`), UNIQUE INDEX \`IDX_335c460cb92f7b8da63d33a420\` (\`source_id\`, \`page_type_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`field_definitions\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`field_name\` varchar(100) NOT NULL, \`data_type\` enum ('string', 'number', 'boolean', 'date', 'url', 'email', 'json', 'array', 'html', 'text') NOT NULL, \`validation_rules\` json NULL, \`transformation_rules\` json NULL, \`is_required\` tinyint NOT NULL DEFAULT 0, \`description\` text NULL, UNIQUE INDEX \`IDX_af50108f0a3654fa27fcbfba04\` (\`field_name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cache_entries\` (\`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT, \`cache_key\` varchar(255) NOT NULL, \`cache_value\` longtext NOT NULL, \`expires_at\` timestamp NOT NULL, \`hit_count\` int NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_727122153244e584c366996a3e\` (\`created_at\`), INDEX \`IDX_4ee5bb647af323bfa4b64b9f45\` (\`expires_at\`), UNIQUE INDEX \`IDX_41b6ffb54b6b090f8bb29cded2\` (\`cache_key\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`anime_genres\` (\`anime_id\` bigint UNSIGNED NOT NULL, \`genre_id\` bigint UNSIGNED NOT NULL, INDEX \`IDX_26c6171c309c7083f2c841fcea\` (\`anime_id\`), INDEX \`IDX_b8fea2c497bd1ed5fd57ac23b0\` (\`genre_id\`), PRIMARY KEY (\`anime_id\`, \`genre_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`crawl_logs\` ADD CONSTRAINT \`FK_aea5b9190a22274d80784b7a035\` FOREIGN KEY (\`job_id\`) REFERENCES \`crawl_jobs\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`crawl_jobs\` ADD CONSTRAINT \`FK_967b6d0bdab9d0811ea3d63316c\` FOREIGN KEY (\`source_id\`) REFERENCES \`sources\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`anime_update_history\` ADD CONSTRAINT \`FK_9564c07cc4861432b4ec9424d5c\` FOREIGN KEY (\`anime_id\`) REFERENCES \`anime\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`download_links\` ADD CONSTRAINT \`FK_cddafb1e1ffdcc3fad35cf46d1f\` FOREIGN KEY (\`episode_id\`) REFERENCES \`episodes\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`episodes\` ADD CONSTRAINT \`FK_9d3063c2bbc60082263d00c291f\` FOREIGN KEY (\`anime_id\`) REFERENCES \`anime\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`anime\` ADD CONSTRAINT \`FK_f6a96de0204d37aae93e2b62e6d\` FOREIGN KEY (\`source_id\`) REFERENCES \`sources\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`source_health\` ADD CONSTRAINT \`FK_f287ed7b8766e711115e8d846f6\` FOREIGN KEY (\`source_id\`) REFERENCES \`sources\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`url_templates\` ADD CONSTRAINT \`FK_98d0f9b6d5fa566e6fd936eb2dd\` FOREIGN KEY (\`source_id\`) REFERENCES \`sources\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`url_templates\` ADD CONSTRAINT \`FK_739a2538e755e0f5a941730d26d\` FOREIGN KEY (\`page_type_id\`) REFERENCES \`page_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`url_patterns\` ADD CONSTRAINT \`FK_d790bb68cca134ba4612b853001\` FOREIGN KEY (\`source_id\`) REFERENCES \`sources\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`url_patterns\` ADD CONSTRAINT \`FK_ce188c58b85e07971b858232109\` FOREIGN KEY (\`page_type_id\`) REFERENCES \`page_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`url_history\` ADD CONSTRAINT \`FK_8796a71d67a5a895daa93b4c102\` FOREIGN KEY (\`source_id\`) REFERENCES \`sources\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`url_history\` ADD CONSTRAINT \`FK_0715e0ca3d6332203c194ff4222\` FOREIGN KEY (\`page_type_id\`) REFERENCES \`page_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`url_history\` ADD CONSTRAINT \`FK_f69ee755a4293c1691e51b87608\` FOREIGN KEY (\`template_id\`) REFERENCES \`url_templates\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`source_headers\` ADD CONSTRAINT \`FK_e57f9fd1412afa14d5253c7a370\` FOREIGN KEY (\`source_id\`) REFERENCES \`sources\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`selectors\` ADD CONSTRAINT \`FK_f1840e854419443d911be1e297f\` FOREIGN KEY (\`selector_type_id\`) REFERENCES \`selector_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`selector_performance\` ADD CONSTRAINT \`FK_9a79495e3d5c96318181ae6e287\` FOREIGN KEY (\`selector_id\`) REFERENCES \`selectors\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`selector_performance\` ADD CONSTRAINT \`FK_80016cb606d1f915d596cec62fd\` FOREIGN KEY (\`source_id\`) REFERENCES \`sources\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`selector_performance\` ADD CONSTRAINT \`FK_c0b17477baf0121706a6ccb762c\` FOREIGN KEY (\`page_type_id\`) REFERENCES \`page_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`selector_fallbacks\` ADD CONSTRAINT \`FK_d2719b8e452151b3a934d9d7360\` FOREIGN KEY (\`primary_selector_id\`) REFERENCES \`selectors\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`selector_fallbacks\` ADD CONSTRAINT \`FK_8abf4f61c6c9102fbf8894ee5f4\` FOREIGN KEY (\`fallback_selector_id\`) REFERENCES \`selectors\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`page_selectors\` ADD CONSTRAINT \`FK_a5daeb6664ca5a5a07d29abdb8c\` FOREIGN KEY (\`source_id\`) REFERENCES \`sources\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`page_selectors\` ADD CONSTRAINT \`FK_6bb1975aff60166ff99563ad061\` FOREIGN KEY (\`page_type_id\`) REFERENCES \`page_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`page_selectors\` ADD CONSTRAINT \`FK_1f63b895fc5a6b2e9c7bbb948ed\` FOREIGN KEY (\`selector_id\`) REFERENCES \`selectors\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`crawl_strategies\` ADD CONSTRAINT \`FK_7acb2ec1d957fc603179a99a302\` FOREIGN KEY (\`source_id\`) REFERENCES \`sources\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`crawl_strategies\` ADD CONSTRAINT \`FK_1b9d7d2609e9756be2ebb2593e4\` FOREIGN KEY (\`page_type_id\`) REFERENCES \`page_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`anime_genres\` ADD CONSTRAINT \`FK_26c6171c309c7083f2c841fcea8\` FOREIGN KEY (\`anime_id\`) REFERENCES \`anime\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`anime_genres\` ADD CONSTRAINT \`FK_b8fea2c497bd1ed5fd57ac23b04\` FOREIGN KEY (\`genre_id\`) REFERENCES \`genres\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`anime_genres\` DROP FOREIGN KEY \`FK_b8fea2c497bd1ed5fd57ac23b04\``);
        await queryRunner.query(`ALTER TABLE \`anime_genres\` DROP FOREIGN KEY \`FK_26c6171c309c7083f2c841fcea8\``);
        await queryRunner.query(`ALTER TABLE \`crawl_strategies\` DROP FOREIGN KEY \`FK_1b9d7d2609e9756be2ebb2593e4\``);
        await queryRunner.query(`ALTER TABLE \`crawl_strategies\` DROP FOREIGN KEY \`FK_7acb2ec1d957fc603179a99a302\``);
        await queryRunner.query(`ALTER TABLE \`page_selectors\` DROP FOREIGN KEY \`FK_1f63b895fc5a6b2e9c7bbb948ed\``);
        await queryRunner.query(`ALTER TABLE \`page_selectors\` DROP FOREIGN KEY \`FK_6bb1975aff60166ff99563ad061\``);
        await queryRunner.query(`ALTER TABLE \`page_selectors\` DROP FOREIGN KEY \`FK_a5daeb6664ca5a5a07d29abdb8c\``);
        await queryRunner.query(`ALTER TABLE \`selector_fallbacks\` DROP FOREIGN KEY \`FK_8abf4f61c6c9102fbf8894ee5f4\``);
        await queryRunner.query(`ALTER TABLE \`selector_fallbacks\` DROP FOREIGN KEY \`FK_d2719b8e452151b3a934d9d7360\``);
        await queryRunner.query(`ALTER TABLE \`selector_performance\` DROP FOREIGN KEY \`FK_c0b17477baf0121706a6ccb762c\``);
        await queryRunner.query(`ALTER TABLE \`selector_performance\` DROP FOREIGN KEY \`FK_80016cb606d1f915d596cec62fd\``);
        await queryRunner.query(`ALTER TABLE \`selector_performance\` DROP FOREIGN KEY \`FK_9a79495e3d5c96318181ae6e287\``);
        await queryRunner.query(`ALTER TABLE \`selectors\` DROP FOREIGN KEY \`FK_f1840e854419443d911be1e297f\``);
        await queryRunner.query(`ALTER TABLE \`source_headers\` DROP FOREIGN KEY \`FK_e57f9fd1412afa14d5253c7a370\``);
        await queryRunner.query(`ALTER TABLE \`url_history\` DROP FOREIGN KEY \`FK_f69ee755a4293c1691e51b87608\``);
        await queryRunner.query(`ALTER TABLE \`url_history\` DROP FOREIGN KEY \`FK_0715e0ca3d6332203c194ff4222\``);
        await queryRunner.query(`ALTER TABLE \`url_history\` DROP FOREIGN KEY \`FK_8796a71d67a5a895daa93b4c102\``);
        await queryRunner.query(`ALTER TABLE \`url_patterns\` DROP FOREIGN KEY \`FK_ce188c58b85e07971b858232109\``);
        await queryRunner.query(`ALTER TABLE \`url_patterns\` DROP FOREIGN KEY \`FK_d790bb68cca134ba4612b853001\``);
        await queryRunner.query(`ALTER TABLE \`url_templates\` DROP FOREIGN KEY \`FK_739a2538e755e0f5a941730d26d\``);
        await queryRunner.query(`ALTER TABLE \`url_templates\` DROP FOREIGN KEY \`FK_98d0f9b6d5fa566e6fd936eb2dd\``);
        await queryRunner.query(`ALTER TABLE \`source_health\` DROP FOREIGN KEY \`FK_f287ed7b8766e711115e8d846f6\``);
        await queryRunner.query(`ALTER TABLE \`anime\` DROP FOREIGN KEY \`FK_f6a96de0204d37aae93e2b62e6d\``);
        await queryRunner.query(`ALTER TABLE \`episodes\` DROP FOREIGN KEY \`FK_9d3063c2bbc60082263d00c291f\``);
        await queryRunner.query(`ALTER TABLE \`download_links\` DROP FOREIGN KEY \`FK_cddafb1e1ffdcc3fad35cf46d1f\``);
        await queryRunner.query(`ALTER TABLE \`anime_update_history\` DROP FOREIGN KEY \`FK_9564c07cc4861432b4ec9424d5c\``);
        await queryRunner.query(`ALTER TABLE \`crawl_jobs\` DROP FOREIGN KEY \`FK_967b6d0bdab9d0811ea3d63316c\``);
        await queryRunner.query(`ALTER TABLE \`crawl_logs\` DROP FOREIGN KEY \`FK_aea5b9190a22274d80784b7a035\``);
        await queryRunner.query(`DROP INDEX \`IDX_b8fea2c497bd1ed5fd57ac23b0\` ON \`anime_genres\``);
        await queryRunner.query(`DROP INDEX \`IDX_26c6171c309c7083f2c841fcea\` ON \`anime_genres\``);
        await queryRunner.query(`DROP TABLE \`anime_genres\``);
        await queryRunner.query(`DROP INDEX \`IDX_41b6ffb54b6b090f8bb29cded2\` ON \`cache_entries\``);
        await queryRunner.query(`DROP INDEX \`IDX_4ee5bb647af323bfa4b64b9f45\` ON \`cache_entries\``);
        await queryRunner.query(`DROP INDEX \`IDX_727122153244e584c366996a3e\` ON \`cache_entries\``);
        await queryRunner.query(`DROP TABLE \`cache_entries\``);
        await queryRunner.query(`DROP INDEX \`IDX_af50108f0a3654fa27fcbfba04\` ON \`field_definitions\``);
        await queryRunner.query(`DROP TABLE \`field_definitions\``);
        await queryRunner.query(`DROP INDEX \`IDX_335c460cb92f7b8da63d33a420\` ON \`crawl_strategies\``);
        await queryRunner.query(`DROP INDEX \`IDX_9c48bb32c66ff1e862eb5c63d3\` ON \`crawl_strategies\``);
        await queryRunner.query(`DROP TABLE \`crawl_strategies\``);
        await queryRunner.query(`DROP INDEX \`IDX_ea564f9ee4653428fa6d12f94e\` ON \`page_selectors\``);
        await queryRunner.query(`DROP INDEX \`IDX_ec2101fb6578f5461937857ca5\` ON \`page_selectors\``);
        await queryRunner.query(`DROP TABLE \`page_selectors\``);
        await queryRunner.query(`DROP INDEX \`IDX_fbe135c9203e18689726da64d8\` ON \`selector_fallbacks\``);
        await queryRunner.query(`DROP INDEX \`IDX_0769c47ec4c57c433d7d7f5354\` ON \`selector_fallbacks\``);
        await queryRunner.query(`DROP TABLE \`selector_fallbacks\``);
        await queryRunner.query(`DROP INDEX \`IDX_8b29bfc2ce8062a6670f632ca1\` ON \`selector_performance\``);
        await queryRunner.query(`DROP INDEX \`IDX_16575e5e8cdd24246c64ac8022\` ON \`selector_performance\``);
        await queryRunner.query(`DROP INDEX \`IDX_a005831fdd760a68fef267822d\` ON \`selector_performance\``);
        await queryRunner.query(`DROP TABLE \`selector_performance\``);
        await queryRunner.query(`DROP INDEX \`IDX_497ad93eab57e405365304266c\` ON \`selectors\``);
        await queryRunner.query(`DROP INDEX \`IDX_d3a18a0a7df1bbadd26788cf4d\` ON \`selectors\``);
        await queryRunner.query(`DROP INDEX \`IDX_8d1bad2f2313c639e3c396c746\` ON \`selectors\``);
        await queryRunner.query(`DROP INDEX \`IDX_da03f3f8b37c9ffe0fa499e2ea\` ON \`selectors\``);
        await queryRunner.query(`DROP TABLE \`selectors\``);
        await queryRunner.query(`DROP INDEX \`IDX_56a4ddb94ed60419498db630ff\` ON \`selector_types\``);
        await queryRunner.query(`DROP TABLE \`selector_types\``);
        await queryRunner.query(`DROP INDEX \`IDX_bf876dcdbfdd747a160338cb5e\` ON \`source_headers\``);
        await queryRunner.query(`DROP INDEX \`IDX_8152d28e6dd1ad99e693ec7f6f\` ON \`source_headers\``);
        await queryRunner.query(`DROP TABLE \`source_headers\``);
        await queryRunner.query(`DROP INDEX \`IDX_f9589d4ba0d8cd0907a706b17f\` ON \`url_history\``);
        await queryRunner.query(`DROP INDEX \`IDX_6a3efcaf5f22c5fd41e663700e\` ON \`url_history\``);
        await queryRunner.query(`DROP TABLE \`url_history\``);
        await queryRunner.query(`DROP INDEX \`IDX_423c12a15a879d69090f399d76\` ON \`url_patterns\``);
        await queryRunner.query(`DROP TABLE \`url_patterns\``);
        await queryRunner.query(`DROP INDEX \`IDX_bb54bd9fe3cbfb212914178ba5\` ON \`url_templates\``);
        await queryRunner.query(`DROP INDEX \`IDX_535b0f3055fea368253127eb7e\` ON \`url_templates\``);
        await queryRunner.query(`DROP TABLE \`url_templates\``);
        await queryRunner.query(`DROP INDEX \`IDX_237d2788374796cac460d70106\` ON \`page_types\``);
        await queryRunner.query(`DROP TABLE \`page_types\``);
        await queryRunner.query(`DROP INDEX \`IDX_8809b5347e14710b28d9dfd2d8\` ON \`source_health\``);
        await queryRunner.query(`DROP INDEX \`IDX_3382deed6264090bdea4c03c11\` ON \`source_health\``);
        await queryRunner.query(`DROP TABLE \`source_health\``);
        await queryRunner.query(`DROP INDEX \`IDX_9518ae1bc1cb241a19e4247624\` ON \`sources\``);
        await queryRunner.query(`DROP INDEX \`IDX_9a5cea873a16f3b91692a889d1\` ON \`sources\``);
        await queryRunner.query(`DROP TABLE \`sources\``);
        await queryRunner.query(`DROP INDEX \`IDX_eb697220f0bea58bc6b034dc74\` ON \`anime\``);
        await queryRunner.query(`DROP INDEX \`IDX_3357ef66530ded8070af8db20b\` ON \`anime\``);
        await queryRunner.query(`DROP INDEX \`IDX_fff1bb5201c112dbc7235cec57\` ON \`anime\``);
        await queryRunner.query(`DROP INDEX \`IDX_ee8f7d2e05dacf165cb7badb19\` ON \`anime\``);
        await queryRunner.query(`DROP INDEX \`IDX_5d0ffd2a6f4ce38af5e2f0a52f\` ON \`anime\``);
        await queryRunner.query(`DROP TABLE \`anime\``);
        await queryRunner.query(`DROP INDEX \`IDX_d1cbe4fe39bdfc77c76e94eada\` ON \`genres\``);
        await queryRunner.query(`DROP INDEX \`IDX_f105f8230a83b86a346427de94\` ON \`genres\``);
        await queryRunner.query(`DROP TABLE \`genres\``);
        await queryRunner.query(`DROP INDEX \`IDX_5729db763fdc1c5a943593a8cb\` ON \`episodes\``);
        await queryRunner.query(`DROP INDEX \`IDX_9d3063c2bbc60082263d00c291\` ON \`episodes\``);
        await queryRunner.query(`DROP INDEX \`IDX_bb36da96b51635996fc7fa4c7f\` ON \`episodes\``);
        await queryRunner.query(`DROP TABLE \`episodes\``);
        await queryRunner.query(`DROP INDEX \`IDX_cddafb1e1ffdcc3fad35cf46d1\` ON \`download_links\``);
        await queryRunner.query(`DROP INDEX \`IDX_a5fb8506d10d1e5ec4e93a0154\` ON \`download_links\``);
        await queryRunner.query(`DROP INDEX \`IDX_882318f0444faea04ee7d76ea6\` ON \`download_links\``);
        await queryRunner.query(`DROP TABLE \`download_links\``);
        await queryRunner.query(`DROP INDEX \`IDX_9564c07cc4861432b4ec9424d5\` ON \`anime_update_history\``);
        await queryRunner.query(`DROP INDEX \`IDX_d98d6258f0b70918ee4b2060ab\` ON \`anime_update_history\``);
        await queryRunner.query(`DROP TABLE \`anime_update_history\``);
        await queryRunner.query(`DROP INDEX \`IDX_218a9499fe36d693fe18a9d505\` ON \`crawl_jobs\``);
        await queryRunner.query(`DROP INDEX \`IDX_967b6d0bdab9d0811ea3d63316\` ON \`crawl_jobs\``);
        await queryRunner.query(`DROP INDEX \`IDX_13ffa2e790ff4931f9b116e803\` ON \`crawl_jobs\``);
        await queryRunner.query(`DROP INDEX \`IDX_3080b5173e786addd7def0c82e\` ON \`crawl_jobs\``);
        await queryRunner.query(`DROP INDEX \`IDX_9a2ecfc045315c5119c9caed35\` ON \`crawl_jobs\``);
        await queryRunner.query(`DROP TABLE \`crawl_jobs\``);
        await queryRunner.query(`DROP INDEX \`IDX_aea5b9190a22274d80784b7a03\` ON \`crawl_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_15dd00f74d60c1b194e654a2c1\` ON \`crawl_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_8796d9fb5c3a92b85a84fd53f8\` ON \`crawl_logs\``);
        await queryRunner.query(`DROP TABLE \`crawl_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_61423160d46bd87e20380712aa\` ON \`queue_jobs\``);
        await queryRunner.query(`DROP INDEX \`IDX_68ced099a28e1d2d9b88223f64\` ON \`queue_jobs\``);
        await queryRunner.query(`DROP INDEX \`IDX_5d66d6a093d8d7ac1a879b7a30\` ON \`queue_jobs\``);
        await queryRunner.query(`DROP TABLE \`queue_jobs\``);
    }

}
