export enum Envs {
  DATABASE_URL = 'DATABASE_URL',
  RMQ_URL = 'RMQ_URL',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  JWT_REF_EXPIRES_IN = 'JWT_REF_EXPIRES_IN',
  BROWSER_HEADLESS = 'BROWSER_HEADLESS',
}
