export enum Envs {
  APP_ENV = 'APP_ENV',
  DATABASE_URL = 'DATABASE_URL',
  RMQ_URL = 'RMQ_URL',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  JWT_REF_EXPIRES_IN = 'JWT_REF_EXPIRES_IN',
}
